# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01446f32956a75555545b15bc3365e126375364583dc4fee9327ac1ef6da9801bd7039f1e1ffbd014001d5e65fc660a1a5c069d7c9008673bb963f8a996ab7db

test:
  secret_key_base: 6ef35a036f22a4f83c198722adaa9b94b9e6f41e44af53362541cba477924d372d12d514d9fd51151e518684a88cee221147b1405dd199895db84d401f692a99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
